# Drupal with MySQL
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial Drupal setup,
# Database type: MySQL
# ADVANCED OPTIONS; Database host: mysql

# To run the stack run
# sudo docker stack deploy -c mcit-docker-compose.yml mcit-drupal
# To stop the stack run
# sudo docker stack rm mcit-drupal

# Maintainance user
# Username: mcit_user
# Password: Secret@mcit11

version: '3.1'

services:
  dbvear_cms:
    image: dbeaver/cloudbeaver:latest
    restart: always
    container_name: dbvear
    ports:
      - 8084:8978
      