version: '3.1'

services:
   # Database management in a single php file
  # It is basically the admin panel for the database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8086:8080
